### ISSUE TITLE
Reason for banning ‘y’ endings

### ISSUE THREAD

**Issue by aryanGajelli** [boxspah/picture-shiritori#1]
What is the reason for banning words that end in a ‘y’. Is it to follow the original style? Or is it because words that start with ‘y’ are hard to draw? I think if we should allow ‘y’ endings as the game can get quite a lot more challenging or at the least there should be two levels of playing.

**Comment by boxspah** [comment]
Words ending with 'y' are not allowed because there are very few drawable objects that begin with 'y'. The use of 'y' words also encourages memorizing sets of words rather than reacting spontaneously.

Picture shiritori is less a competition of stumping your opponent with hard words, but an artistic and linguistic spar. This is why "artificial" words are discouraged; it is not a speed typing competition.

**Comment by aryanGajelli** [comment]
Thanks for the clarification
